#!/bin/sh

set -e

if [ "${1}" = "configure" ] ; then
	python3 /usr/share/openstack-dashboard/manage.py collectstatic --clear --noinput
	python3 /usr/share/openstack-dashboard/manage.py compress --force
	if [ -f /var/lib/openstack-dashboard/secret-key/.secret_key_store ]; then
		rm /var/lib/openstack-dashboard/secret-key/.secret_key_store
	fi
	chown -R horizon:horizon /var/lib/openstack-dashboard
fi

#DEBHELPER#
